import { defineCollection, z } from "astro:content";
import { glob } from "astro/loaders";

const people = defineCollection({
  loader: glob({ pattern: "**/*.md", base: "src/content/people" }),
  schema: z.object({
    name: z.string(),
    avatar: z.string(),
    tagline: z.string(),
    bio: z.string(),
    role: z.string().optional(),
    twitter: z.string().optional(),
    github: z.string().optional(),
    linkedin: z.string().optional(),
    website: z.string().url().optional(),
    // Free-form list of canonical external profile URLs emitted as Person
    // JSON-LD `sameAs`. Keep this as the source of truth for entity-level SEO;
    // the shortcut handle fields above (twitter/github/linkedin) feed into it
    // at render time.
    sameAs: z.array(z.string().url()).optional(),
    products: z
      .array(
        z.object({
          name: z.string(),
          url: z.string().url(),
        }),
      )
      .optional(),
  }),
});

const journeys = defineCollection({
  loader: glob({ pattern: "**/*.md", base: "src/content/journeys" }),
  schema: z.object({
    title: z.string(),
    subtitle: z.string(),
    person: z.string(),
    date: z.coerce.date(),
    lessons: z.array(z.string()),
  }),
});

const events = defineCollection({
  loader: glob({ pattern: "**/*.md", base: "src/content/events" }),
  schema: z.object({
    title: z.string(),
    subtitle: z.string(),
    date: z.coerce.date(),
    location: z.string(),
    link: z.string().url().optional(),
    image: z.string().optional(),
    // Optional hand-crafted social card. When set, it overrides the
    // templated /og/events/<slug>.png card generated by scripts/gen_og.py.
    ogImage: z.string().optional(),
    presenters: z.array(z.string()),
  }),
});

export const collections = { people, journeys, events };
